#========================================
# General settings
#========================================
logging:
  level:
    root: INFO

openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

spring:
  application:
    name: teamssender

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

azure:
  ad:
    "2281":
      user: ${AZURE_USER}
      clientId: ${AZURE_CLIENT_ID}
      tenantId: ${AZURE_TENANT_ID}
      clientSecret: ${AZURE_CLIENT_SECRET}
      authorityUrl: ${AZURE_AUTHORITY_URL}
      redirectUri: ${AZURE_REDIRECT_URI}
      loginUrl: ${AZURE_LOGIN_URL}
      scopes: ${AZURE_SCOPES}

graph:
  base-url: https://graph.microsoft.com/v1.0
